# Install script for directory: /home/panxiaogong/3rdparty/android/opencv-3.1.0/modules

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_install/opencv")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "0")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "TRUE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/calib3d/.calib3d/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/core/.core/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/cudaarithm/.cudaarithm/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/cudabgsegm/.cudabgsegm/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/cudacodec/.cudacodec/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/cudafeatures2d/.cudafeatures2d/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/cudafilters/.cudafilters/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/cudaimgproc/.cudaimgproc/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/cudalegacy/.cudalegacy/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/cudaobjdetect/.cudaobjdetect/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/cudaoptflow/.cudaoptflow/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/cudastereo/.cudastereo/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/cudawarping/.cudawarping/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/cudev/.cudev/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/features2d/.features2d/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/flann/.flann/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/highgui/.highgui/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/imgcodecs/.imgcodecs/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/imgproc/.imgproc/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/java/.java/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/ml/.ml/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/objdetect/.objdetect/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/photo/.photo/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/python/.python/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/shape/.shape/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/stitching/.stitching/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/superres/.superres/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/ts/.ts/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/video/.video/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/videoio/.videoio/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/videostab/.videostab/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/viz/.viz/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/world/.world/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/core/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/flann/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/imgproc/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/ml/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/photo/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/video/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/imgcodecs/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/shape/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/videoio/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/highgui/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/objdetect/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/superres/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/features2d/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/calib3d/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/stitching/cmake_install.cmake")
  include("/home/panxiaogong/3rdparty/android/opencv-3.1.0/build_android/modules/videostab/cmake_install.cmake")

endif()

